[tox]
min_version = 4.0
env_list = py3{8,9,10,11}-ansible{29,210,30,40,50,60,70,80}
skip_missing_interpreters = true
isolated_build = false

[testenv]
allowlist_externals = 
    bash
    molecule
passenv = 
    *
setenv =
    ANSIBLE_ROLES_PATH = {toxinidir}/../:{toxinidir}/../roles
    ANSIBLE_COLLECTIONS_PATH = {toxinidir}/../collections
    ANSIBLE_FORCE_COLOR = true
    PY_COLORS = 1
deps =
    -r tox-requirements.txt
    ansible29: ansible>=2.9,<2.10
    ansible210: ansible>=2.10,<2.11
    ansible30: ansible>=3.0,<4.0
    ansible40: ansible>=4.0,<5.0
    ansible50: ansible>=5.0,<6.0
    ansible60: ansible>=6.0,<7.0
    ansible70: ansible>=7.0,<8.0
    ansible80: ansible>=8.0,<9.0
commands =
    molecule test -s podman_minimal

[testenv:lint]
deps =
    yamllint
    ansible-lint
commands =
    yamllint .
    ansible-lint

[testenv:syntax]
commands =
    molecule syntax -s podman_minimal

[testenv:create]
commands =
    molecule create -s podman_minimal

[testenv:converge]
commands =
    molecule converge -s podman_minimal

[testenv:verify]
commands =
    molecule verify -s podman_minimal

[testenv:destroy]
commands =
    molecule destroy -s podman_minimal

[testenv:idempotence]
commands =
    molecule converge -s podman_minimal -- --tags=idempotence-check
